theme: jekyll-theme-cayman

title: Gabriel Vieira
description: ğŸ‘¨ğŸ»â€ğŸ’» Bem-vindos ao meu Github!

navbar-links:
  About Me: "Sobre Mim"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"

